# Generated by Django 2.1.7 on 2019-02-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('devicemac', models.CharField(blank=True, default='', max_length=20)),
                ('deviceon', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('devicemac',),
            },
        ),
    ]
