# Generated by Django 2.1.7 on 2019-03-16 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devicesapp', '0002_auto_20190305_0100'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileupload', models.FileField(upload_to='uploads/')),
                ('comment', models.CharField(blank=True, default='', max_length=20)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devicesapp.DeviceList')),
            ],
            options={
                'ordering': ('device',),
            },
        ),
    ]
